version: 0.2

phases:
  pre_build:
      commands:
        - echo login in aws ECR
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 497559131610.dkr.ecr.us-east-1.amazonaws.com
	- REPOSITORY_URI=497559131610.dkr.ecr.us-east-1.amazonaws.com
        - echo login success                  
  build:
    commands:
       - echo build started...
       - dotnet restore ./QuantityMeasurement/QuantityMeasurement.csproj
       - dotnet build ./QuantityMeasurement/QuantityMeasurement.csproj -c Release
       - dotnet publish ./QuantityMeasurement/QuantityMeasurement.csproj -c Release
       - echo Building the Docker image...
       - docker build -t $REPOSITORY_URI:quantity_measurement_api-${CODEBUILD_BUILD_NUMBER} -f Dockerfile ./QuantityMeasurement/.
  post_build:
    commands:
       - echo Build completed on `date`
       - echo Pushing the Docker images...
       - docker push $REPOSITORY_URI:quantity_measurement_api${CODEBUILD_BUILD_NUMBER}
       - echo Writing image definitions file...
       - printf '[{"name":"IL_ECS_AlincSupportCtr_DU","imageUri":"%s"}]' $REPOSITORY_URI:quantity_measurement_api-${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
       - cat imagedefinitions.json
artifacts:
  files: '**/*'
  discard-paths: yes